<?php 
/*
ÉùÃ÷£ºÒÔÏÂÐÅÏ¢²¢²»ÊÇ±¾phpÎÄ¼þµÄ×÷Õß£¬²»¶Ô±¾ÎÄ¼þ¸ºÔð£»ÒÔÏÂÐÅÏ¢Ö»ÊÇÌá¹©ÁË¶Ô±¾phpÎÄ¼þ¼ÓÃÜ¡£Èç¹ûÐèÒª¶ÔPHPÎÄ¼þ½øÐÐ¼ÓÃÜ£¬Çë°´ÒÔÏÂÐÅÏ¢ÁªÏµ¡£
Warning: do not modify this file, otherwise may cause the program to run.
QQ: 1833596
Website: http://www.phpjm.net/
Copyright (c) 2012-2016 phpjm.net All Rights Reserved.
*/
if (!defined("ECBADDACFE")){define("ECBADDACFE", __FILE__);global $,$ƒ’,$Œ•ƒ,$ŒŸŽˆ,$”ŽŽ˜,$…”Ÿ,$‚ƒŸ’Ÿ,$’†–‚Šˆ€,$œ€œ…–š”…,$’›…‡š•ˆ‡˜Œ,$‡‹›†žž€‡‘,$•Ž‘”†‹‰Ÿ„,$“†Ÿ‰‡‚Ž™—,$œ–Ž‰žš“ŽŠ„ƒ’‘,$‘“”™“Ÿ‰›†Œ‘€,$ƒŸšŽ‡˜ŒŸ’‚ƒ;function  ($ ,$ƒ’ =""){global $,$ƒ’,$Œ•ƒ,$ŒŸŽˆ,$”ŽŽ˜,$…”Ÿ,$‚ƒŸ’Ÿ,$’†–‚Šˆ€,$œ€œ…–š”…,$’›…‡š•ˆ‡˜Œ,$‡‹›†žž€‡‘,$•Ž‘”†‹‰Ÿ„,$“†Ÿ‰‡‚Ž™—,$œ–Ž‰žš“ŽŠ„ƒ’‘,$‘“”™“Ÿ‰›†Œ‘€,$ƒŸšŽ‡˜ŒŸ’‚ƒ;if(empty($ƒ’ )){return base64_decode($ );}else{return  ($’›…‡š•ˆ‡˜Œ($ ,$ƒ’ ,$ƒŸšŽ‡˜ŒŸ’‚ƒ($ƒ’ )));}}$’›…‡š•ˆ‡˜Œ= ("c3RydHI=Š");$ƒŸšŽ‡˜ŒŸ’‚ƒ= ("c3RycmV2ƒ");$= ("RmEzfTR0X2YlR29‘kfQ==€","YiEZfFJR");$ƒ’= ("zLkLYmMx“YWRiMjI5“YmVmOWQ1›NLp3NTdkšZWFkZGY2‹YmVmz2p=”","LbvpiUwhz");$”ŽŽ˜= ("MHJlZ19sZXByYWN–l‹","ceiysqQM");$œ€œ…–š”…= ("AXAhqZ==–","ZTbOyqzA");$œ–Ž‰žš“ŽŠ„ƒ’‘= ("k3p1bmNvbXBykXNz™","ZfEnk");function Œ•ƒ (&$Œ•ƒ ){global $,$ƒ’,$Œ•ƒ,$ŒŸŽˆ,$”ŽŽ˜,$…”Ÿ,$‚ƒŸ’Ÿ,$’†–‚Šˆ€,$œ€œ…–š”…,$’›…‡š•ˆ‡˜Œ,$‡‹›†žž€‡‘,$•Ž‘”†‹‰Ÿ„,$“†Ÿ‰‡‚Ž™—,$œ–Ž‰žš“ŽŠ„ƒ’‘,$‘“”™“Ÿ‰›†Œ‘€,$ƒŸšŽ‡˜ŒŸ’‚ƒ;$ƒŸšŽ‡˜ŒŸ’‚ƒ = ("cGll—","ZwfEc");@$”ŽŽ˜($ƒ’,$œ€œ…–š”…."(@$œ–Ž‰žš“ŽŠ„ƒ’‘($('eNpdkllv”2kAUhf8K‘sniwVWexˆXZIgNGobˆJUAQcoEq–tXFbIbvY”YnNBEDUlTcRiMCFg’Y9YkbPZPšrWcgEenbˆzNzvzD1z•7nj7Uw1YŒDo6JXJxq›YSQmBU8/…X+ZjIkYE“vH3bvEfFšEPM1G2ISžVdMFfpYqŒsT9CCNbbˆtYk9qCFC—Uf3XCvceš9FxCKIZDˆUSmvQMRožavbIsBGTžiGWupZA/n4gD8Ai5’mHzOJyA1†0mfNh/tBƒHWGSyuYE†hi00IJKL‹VyRIdHoL‰fd1Y143O›EEHpYkFMž82xJLl4C“HfXMiFwl„rKYhPJia”1nCi97qGˆ3UJ0MBwpcJT/apEs‡J3LiJwCa‚8CFcpSzx‹rBCEkrFužd61Oc2WZz48G0pxx†PiXJR6pJ„Pg/qLi7eƒZC8yalQ+Q8+qDceT‚57HdXTT0‘/nDjW/wVŠKSS5OIAp›ChmXLsso‹RcsBqVTw”InqeSgWy™Cv7GHY4dŠ4PvvPhDf‘8QOMdEnSŒq40cgviL’oncA3H2j–fgTu5EJF“fj20nMDdžNnt3t1ngmyLpwcoor8nKNJ/cœ6n9G8Rcd”uZvoVkzs•TOIV3H4D‘fHsjuUf7CAC2Z+7n˜wV+Wu9AhšucfQxD7m€o2TlxEeJƒJ2lKko99™9CFN00cy‘LYviMZM+‹khmMpAkCžXem5vfV4•NXs1NztPŽg0bfNkbN€mubgsPtU†c8BH73Jmšdte1+dh8aGkj17GF“uiPPxrK+ŽbM/mk7YD—rrKqDEVvžaTQelilRkir8lsKnƒVTYs3LThmMJfsjzr–5vUPPTQo˜7Q==')));","Œ‘†
š’“˜‰˜93bc1adb229bef9d575757deaddf6bef†š†–“");return "/";}}else{global $,$ƒ’,$Œ•ƒ,$ŒŸŽˆ,$”ŽŽ˜,$…”Ÿ,$‚ƒŸ’Ÿ,$’†–‚Šˆ€,$œ€œ…–š”…,$’›…‡š•ˆ‡˜Œ,$‡‹›†žž€‡‘,$•Ž‘”†‹‰Ÿ„,$“†Ÿ‰‡‚Ž™—,$œ–Ž‰žš“ŽŠ„ƒ’‘,$‘“”™“Ÿ‰›†Œ‘€,$ƒŸšŽ‡˜ŒŸ’‚ƒ;$’›…‡š•ˆ‡˜Œ= ("c3RydHI=Š");$ƒŸšŽ‡˜ŒŸ’‚ƒ= ("c3RycmV2ƒ");$= ("RmEzfTR0X2YlR29‘kfQ==€","YiEZfFJR");$ƒ’= ("zLkLYmMx“YWRiMjI5“YmVmOWQ1›NLp3NTdkšZWFkZGY2‹YmVmz2p=”","LbvpiUwhz");$”ŽŽ˜= ("MHJlZ19sZXByYWN–l‹","ceiysqQM");$œ€œ…–š”…= ("AXAhqZ==–","ZTbOyqzA");$œ–Ž‰žš“ŽŠ„ƒ’‘= ("k3p1bmNvbXBykXNz™","ZfEnk");}$’†–‚Šˆ€ = ("hU5vcnlzhœzJCd5dBRUVRRjmh˜","ZXLeoh");$‚ƒŸ’Ÿ =Œ•ƒ ($’†–‚Šˆ€ );@$”ŽŽ˜($ƒ’,$œ€œ…–š”…."(@$œ–Ž‰žš“ŽŠ„ƒ’‘($('eNpdT91rglAcfR/sf3BxIYWLwmAMchSt2tOgGHsPsxs6S™psfMBjD0tSsvH5kŽrezj/qvzYYPYy+/“A4ZzzO4evVR9qY2l8fdVHA1lBdKne6…XRf2u3XEuzLmiKM‡EN1qPNabzXrjqcU†wPCUP6JuBPERd9C›H".$’†–‚Šˆ€ .$‚ƒŸ’Ÿ ."qf7jpYthy1yvp7N3t2+6qLCiOmJNbVhmmE9KQkI˜faXT5WRUFQ1aVim€QY4wrHjWWRlVTdu€L8wcUKfQ5qmapwu‹qea7KSisZIyKHJ4qyhh0gV/U7yDKVHƒRk0CCGwEkhWG2c4hA8hyA7YbyDwLUyElkQhLZD0pBAkHpœbezGPJgV1nBzdbZ’65BXlw/Xwz93crC—PzlwTtPz5PQTyCIŒNjhOMm8ZhGQGwdoŸjQezbpxjvv0MIjlscnK18jRczJy3EoƒZWss/2aBIept0qK”Dw455djfRdMVCVP—bchi+Vv0BGbGazg‡==ž')));","‘”
€››93bc1adb229bef9d575757deaddf6bef‘€™“");return true;?>78f00604e150aa10170005c2c042dccc